# Generated by Django 4.1.3 on 2022-11-20 19:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=20, verbose_name='name')),
                ('body', models.CharField(default='Anonymous', max_length=150)),
                ('like', models.IntegerField(blank=True, default=0)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
