# Generated by Django 4.1.3 on 2022-11-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subapptw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='like',
            new_name='likes',
        ),
    ]
